### ISSUE TITLE
Week 07 Day 3 - Double Back - 

### ISSUE THREAD

**Issue by mdewey** [msolone/assignments#28]
Over the past couple of weeks we have been learning React and did a variety of projects; and over the last week we have learned a new framework, Vue.js. For this project, go back to a selected project that we did in React and recreate it using Vue.js.

## Requirements

* Recreate a React App in Vue

### Explorer Mode

- [ ] Recreate `Color Picker`. 

### Adventure Mode
- [ ] Recreate `Snowman` 

### Epic Mode
- [x] Recreate `Minesweeper`
 

 *NOTE* Remember that you should also be working on your capstone project this weekend as well.

**Comment by msolone** [comment]
https://github.com/msolone/vue-minesweeper

**Comment by mdewey** [comment]
This is just the default vue app, make sure you pushed the latest version.

**Comment by msolone** [comment]
Whoops, fixed it! My bad..

**Comment by mdewey** [comment]
![Awesome Work!](https://media3.giphy.com/media/WgSDfdd09EXCJNbmQt/200w_d.gif)
